services:
  zookeeper:
     image: confluentinc/cp-zookeeper:7.5.0
     environment:
        ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"  # For internal Docker containers
      - "29092:29092"  # For MacBook (host)
  

  elasticsearch:
    image: elasticsearch:8.18.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false        # Disable security (No HTTPS, No auth)
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200

  postgres:
    image: debezium/postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - 5438:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # connect:
  #   #  image: debezium/connect:2.5
  #    build: .
  #    depends_on:
  #     - kafka
  #     - postgres
  #     - elasticsearch
  #    ports:
  #     - '8083:8083'
  #    environment:
  #     - BOOTSTRAP_SERVERS=kafka:9092
  #     - GROUP_ID=1
  #     - CONFIG_STORAGE_TOPIC=my_connect_config
  #     - OFFSET_STORAGE_TOPIC=my_connect_offset
  #     - STATUS_STORAGE_TOPIC=my_connect_statuses
  #     # - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
  #     # - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
  #     # - KEY_CONVERTER_SCHEMAS_ENABLE=false
  #     # - VALUE_CONVERTER_SCHEMAS_ENABLE=false 

    


  connect:
    build: .
    # depends_on:
    #   - kafka
    #   - postgres
    #   - elasticsearch
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: 'connect-cluster'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-configs'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status'
      CONNECT_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      
     
   


        




        