FROM quay.io/debezium/connect:2.5

# Deploy PostgreSQL JDBC Driver
RUN mkdir -p /kafka/libs && \
    cd /kafka/libs && \
    curl -sO https://jdbc.postgresql.org/download/postgresql-42.5.1.jar

# Deploy Kafka Connect JDBC Connector
RUN mkdir -p /kafka/connect/kafka-connect-jdbc && \
    cd /kafka/connect/kafka-connect-jdbc && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/5.3.2/kafka-connect-jdbc-5.3.2.jar

# Deploy Confluent Elasticsearch Sink Connector and its dependencies
# RUN mkdir -p /kafka/connect/kafka-connect-elasticsearch && \
#     cd /kafka/connect/kafka-connect-elasticsearch && \
#     curl -sO https://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/5.3.2/kafka-connect-elasticsearch-5.3.2.jar && \
#     curl -sO https://repo1.maven.org/maven2/io/searchbox/jest/6.3.1/jest-6.3.1.jar && \
#     curl -sO https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore-nio/4.4.4/httpcore-nio-4.4.4.jar && \
#     curl -sO https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar && \
#     curl -sO https://repo1.maven.org/maven2/org/apache/httpcomponents/httpasyncclient/4.1.1/httpasyncclient-4.1.1.jar && \
#     curl -sO https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar && \
#     curl -sO https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar && \
#     curl -sO https://repo1.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.jar && \
#     curl -sO https://repo1.maven.org/maven2/io/searchbox/jest-common/6.3.1/jest-common-6.3.1.jar && \
#     curl -sO https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar && \
#     curl -sO https://repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar

RUN mkdir -p /kafka/connect/kafka-connect-elasticsearch && \
    cd /kafka/connect/kafka-connect-elasticsearch && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/13.0.0/kafka-connect-elasticsearch-13.0.0.jar && \
    curl -sO https://repo1.maven.org/maven2/io/searchbox/jest/6.3.1/jest-6.3.1.jar && \
    curl -sO https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore-nio/4.4.15/httpcore-nio-4.4.15.jar && \
    curl -sO https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar && \
    curl -sO https://repo1.maven.org/maven2/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar && \
    curl -sO https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar && \
    curl -sO https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar && \
    curl -sO https://repo1.maven.org/maven2/commons-codec/commons-codec/1.15/commons-codec-1.15.jar && \
    curl -sO https://repo1.maven.org/maven2/io/searchbox/jest-common/6.3.1/jest-common-6.3.1.jar && \
    curl -sO https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar && \
    curl -sO https://repo1.maven.org/maven2/com/google/guava/guava/33.0.0-jre/guava-33.0.0-jre.jar
