
services:
   postgres:
     image: postgres:13
     environment:
        POSTGRES_USER: airflow
        POSTGRES_PASSWORD: airflow
        POSTGRES_DB: airflow

   redis:
     image: redis:latest

   airflow-webserver:
      image: apache/airflow:2.9.0
      depends_on:
        - postgres
        - redis
      environment:
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
        - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
        - AIRFLOW__WEBSERVER__DEFAULT_USER=airflow
        - AIRFLOW__WEBSERVER__DEFAULT_PASSWORD=airflow
      volumes:
        - ./dags:/opt/airflow/dags
      command: bash -c "airflow db migrate && airflow webserver"
      ports:
        - "8080:8080"

   airflow-scheduler:
      image: apache/airflow:2.9.0
      depends_on:
        - airflow-webserver
      environment:
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
        - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      volumes:
        - ./dags:/opt/airflow/dags
      command: scheduler 

   airflow-worker:
      image: apache/airflow:2.9.0
      depends_on:
        - airflow-webserver
      environment:
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
        - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
        - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      volumes:
        - ./dags:/opt/airflow/dags
      command: celery worker     
            

